### ISSUE TITLE
Pressing shuffle button on other playlist then "All" crashes

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#14]
it happens on the new update 01.5

**Comment by CaptainTimberTim** [comment]
Oh man, I thought I considered the versioning of the Playlist file when I included the per-playlist shuffle stuff... It seems I didn't
and it is crashing because it expects the next version.

I just fixed it and will update the release again in 1-2minutes. 
So I hope this will not happen after you get the newest release again.

If so, you can open this issue again.
