### ISSUE TITLE
Checkbox for enabling saving song's time feature

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#17]
There is a feature that saves time to file when you stop listening to a song before it ends, so you can start from the place in which you ended when you play the song again. It's useful when you listen to long files but I listen to relatively short songs and music pieces. So this feature is quite annoying to me. When I listen to some random songs from my playlist, quite often the song starts from the middle or at the end. I would like the song to always start from the beginning when I press "start playing this song" (on another song than the current one). 
Could you add a checkbox with which you could enable and disable this feature?

**Comment by CaptainTimberTim** [comment]
I am not sure what you mean.
It sounds like you are saying that there already is a feature that saves the song-progress and if you switch songs back and forth it saves the progress of each song (i.e. Song1 is at 40s, Song2 is at 84s and switching between them would start playing them from those 40s and 84s respectively.).
But such a feature does not exist. 
Or do you _want_ such a feature, but additionally you want to be able to disable it, because of the reasons you said.

I think I won't add such a feature, as I really don't see this music player as a longform-podcast-like player were it would be important to save progress of specific songs.

What I _did_ add is a feature that saves the progress of the last song that was playing when the player was closed.

**Comment by Czapa10** [comment]
No I don't want that feature.
There was a bug which made the songs sometimes start not from the beginning.
I haven't seen this bug for a while so maybe it was accidentally fixed or maybe I'm a lunatic and I saw a bug that wasn't actually there.
Anyhow I'm closing the issue.
I'll reopen it if I see this bug again.

**Comment by CaptainTimberTim** [comment]
haha, alright. nice!
