### ISSUE TITLE
Saving settings and libraries

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#3]
Hello again,

The MPlay3Library.save and MPlay3Settings.save are currently saved in the same directory as executable.
This is a problem because if you just drop executable on desktop it will save MPlay3Library.save and MPlay3Settings.save on desktop. I like my desktop to be very clean so for now I dropped executable to other directory and created shortcut to it on desktop.

![image](https://user-images.githubusercontent.com/39434914/111015276-43319780-83a8-11eb-8085-8292b01f63c3.png)

Windows has special directory for saving stuff like that. You can access it by %appdata% environmental variable.

![image](https://user-images.githubusercontent.com/39434914/111015347-91469b00-83a8-11eb-94fc-7573ec20736d.png)

You could save all paths to separate files, so instead of having MPlay3Library.save file you would have files like:
songs.library
MovieSoundtracks.library

This would save user a lot of time in case of loading huge directories and often directory changes.
It would be useful to be able to see all saved libraries from application UI just like you can see recent session files in RemedyBG.

Regards

**Comment by CaptainTimberTim** [comment]
Hi, 
because I really want this app to not randomly place files somewhere on the users computer (even appdata) I avoided placing them in that folder.
But with your message I thought about it and came up with a solution I like for now. The program will now look on startup if it can find the two save files at the location "%appdata%\Roaming\MPlay3Data", if so, it will overwrite those and not create them in the directory the exe is lying (there is a description of this in the MPlay3Settings.save file as well).

For your second suggestion, I will think about adding something like that in the future. 
I imagined the user to have their music in one location with subfolders of different band and stuff (like I have) and then you only have to load the metadata once, the first time you start the app, then you can always just select all the music based on genre/artist/album. But the problem with that may be that the music needs metadata for this to work properly. I'll think on how to do it more consistent (maybe also based on file-tree location).

Greetings, 
TJ
