### ISSUE TITLE
You can't search for songs with metadata without selecting anything in left columns

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#7]
If you didn't select anything from the left columns, You can only find songs that don't have any metadata in the right column.
So if I have 2 Norah Jones songs in the directory, both have Norah Jones in the filename but only one of them has metadata.
If I type Norah Jones in the right column I would see only one song. This shouldn't be the case.

**Comment by CaptainTimberTim** [comment]
Yeah that is because I only search for song title/filename(for no metadata) in the song column.
I was debating with myself as well if it makes sense to search for artist/album as well in the song column.

The reason you brought up here is enough for me at this point to include the artist/album search in the song column. At least for now, as I still find this to be the best solution. But for now it should fix your problem for sure.

This will also be in the release I want to do this weekend.

Greetings!
